//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenteFitNetriders.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clases()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int id { get; set; }
        public string nombre_clase { get; set; }
        public string nrofesor { get; set; }
        public int plazas { get; set; }
        public System.DateTime fecha_clase { get; set; }
        public System.TimeSpan hora_clase { get; set; }
        public int duracion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
