//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenteFitNetriders.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int id { get; set; }
        public int id_usuario { get; set; }
        public int id_clase { get; set; }
        public string estado { get; set; }
    
        public virtual Clases Clases { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
